/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package encuestasparaestudiantes;

import javax.swing.ImageIcon;

/**
 *
 * @author viivi
 */
public class interfazdeusuario extends javax.swing.JFrame {

    private Object lblresultado;

    /**
     * Creates new form interfazdeusuario
     */
    public interfazdeusuario() {
        initComponents();
        rbtsistemas.setSelected(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoQuecarrerauniversitariaprefieres = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btncomfirmar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        lblmensaje = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbtindustrial = new javax.swing.JRadioButton();
        rbtcivil = new javax.swing.JRadioButton();
        rbtarquitetura = new javax.swing.JRadioButton();
        rbtagronomia = new javax.swing.JRadioButton();
        rbtadministracion = new javax.swing.JRadioButton();
        rbtbacteriologia = new javax.swing.JRadioButton();
        rbtcine = new javax.swing.JRadioButton();
        rbtcomunicacion = new javax.swing.JRadioButton();
        rbtcontaduria = new javax.swing.JRadioButton();
        rbtdeporte = new javax.swing.JRadioButton();
        rbtderecho = new javax.swing.JRadioButton();
        rbtsistemas = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btncomfirmar.setBackground(new java.awt.Color(255, 255, 255));
        btncomfirmar.setText("Confirmar");
        btncomfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomfirmarActionPerformed(evt);
            }
        });

        btnlimpiar.setBackground(new java.awt.Color(255, 255, 255));
        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        lblmensaje.setBackground(new java.awt.Color(0, 0, 0));
        lblmensaje.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Que carrera universitaria prefieres?"));

        GrupoQuecarrerauniversitariaprefieres.add(rbtindustrial);
        rbtindustrial.setText("Ing.Industrial");

        GrupoQuecarrerauniversitariaprefieres.add(rbtcivil);
        rbtcivil.setText("Ing.Civil");

        GrupoQuecarrerauniversitariaprefieres.add(rbtarquitetura);
        rbtarquitetura.setText("Arquitetura ");

        GrupoQuecarrerauniversitariaprefieres.add(rbtagronomia);
        rbtagronomia.setText("Agronomia");
        rbtagronomia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtagronomiaActionPerformed(evt);
            }
        });

        GrupoQuecarrerauniversitariaprefieres.add(rbtadministracion);
        rbtadministracion.setText("Administraciòn");

        GrupoQuecarrerauniversitariaprefieres.add(rbtbacteriologia);
        rbtbacteriologia.setText("Bacteriologia");

        GrupoQuecarrerauniversitariaprefieres.add(rbtcine);
        rbtcine.setText("Cine,Televisiòn y afines");

        GrupoQuecarrerauniversitariaprefieres.add(rbtcomunicacion);
        rbtcomunicacion.setText("Comunicaciòn social");

        GrupoQuecarrerauniversitariaprefieres.add(rbtcontaduria);
        rbtcontaduria.setText("Contaduria");

        GrupoQuecarrerauniversitariaprefieres.add(rbtdeporte);
        rbtdeporte.setText("Deporte y recreaciòn");

        GrupoQuecarrerauniversitariaprefieres.add(rbtderecho);
        rbtderecho.setText("Derecho");

        GrupoQuecarrerauniversitariaprefieres.add(rbtsistemas);
        rbtsistemas.setText("Ing.Sistemas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtagronomia)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(rbtsistemas)
                                    .addGap(8, 8, 8)
                                    .addComponent(rbtadministracion))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbtindustrial)
                                        .addComponent(rbtcivil))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbtderecho)
                                        .addComponent(rbtbacteriologia))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtarquitetura)
                                    .addComponent(rbtcontaduria))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtdeporte)
                                    .addComponent(rbtcomunicacion))))
                        .addGap(0, 57, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(rbtcine)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtsistemas)
                            .addComponent(rbtadministracion))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtindustrial)
                            .addComponent(rbtbacteriologia))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtcivil)
                            .addComponent(rbtderecho))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtarquitetura)
                            .addComponent(rbtcomunicacion)))
                    .addComponent(rbtagronomia))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtcontaduria)
                    .addComponent(rbtdeporte))
                .addGap(26, 26, 26)
                .addComponent(rbtcine)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(btncomfirmar)
                        .addGap(74, 74, 74)
                        .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(lblmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(lblmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncomfirmar)
                    .addComponent(btnlimpiar))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtagronomiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtagronomiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtagronomiaActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
        GrupoQuecarrerauniversitariaprefieres.clearSelection();
        lblmensaje.setText("");
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btncomfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomfirmarActionPerformed
        // TODO add your handling code here:
        String confirmar="La opciòn Seleccionada es: ";
        if(rbtsistemas.isSelected()){
            confirmar+="Ing. Sistemas";
        }
        if(rbtindustrial.isSelected()){
            confirmar+="Ing. Industrial";
        }
        if(rbtcivil.isSelected()){
            confirmar+="Ing. Civil";
        }
        if(rbtarquitetura.isSelected()){
            confirmar+="Arquitetura";
        }
        if(rbtagronomia.isSelected()){
            confirmar+="Angronomia";
        }
        if(rbtadministracion.isSelected()){
            confirmar+="Administraciòn";
        }
        if(rbtbacteriologia.isSelected()){
            confirmar+="Bacteriologia";
        }
        if(rbtcine.isSelected()){
            confirmar+="Cine, Televisiòn y afines";
        }
        if(rbtcomunicacion.isSelected()){
            confirmar+="Comunicaciòn social";
        }
        if(rbtcontaduria.isSelected()){
            confirmar+="Contaduria";
        }
        if(rbtdeporte.isSelected()){
            confirmar+="Deporte y recreaciòn";
        }
        if(rbtderecho.isSelected()){
            confirmar+="Derecho";
        }

        lblmensaje.setText(confirmar);

    }//GEN-LAST:event_btncomfirmarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazdeusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazdeusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazdeusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazdeusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazdeusuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoQuecarrerauniversitariaprefieres;
    private javax.swing.JButton btncomfirmar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblmensaje;
    private javax.swing.JRadioButton rbtadministracion;
    private javax.swing.JRadioButton rbtagronomia;
    private javax.swing.JRadioButton rbtarquitetura;
    private javax.swing.JRadioButton rbtbacteriologia;
    private javax.swing.JRadioButton rbtcine;
    private javax.swing.JRadioButton rbtcivil;
    private javax.swing.JRadioButton rbtcomunicacion;
    private javax.swing.JRadioButton rbtcontaduria;
    private javax.swing.JRadioButton rbtdeporte;
    private javax.swing.JRadioButton rbtderecho;
    private javax.swing.JRadioButton rbtindustrial;
    private javax.swing.JRadioButton rbtsistemas;
    // End of variables declaration//GEN-END:variables
}
